#!/bin/bash

MAX_WORKERS=10
DEBUG=0
OPT="-O2"
WARN=""
ROOT="."
CFLAGS="-pipe -fPIC"
LIBS="-lz -lpthread -ldl"
OUTBIN="server"

CP_ENABLED=0
LUA_ENABLED=0
PLUGIN_BUILD=0

clean () {
	rm -rf objs/* server;
	exit 0;
}

for a in "$@"
do
	if [ $PLUGIN_BUILD -eq 1 ]; then
		CFLAGS="$CFLAGS -DCPLUGIN -Iheaders"
		PLUGIN_NAME="$a"
		OUTBIN="$a.so"
		ROOT="$a"
		break
	fi
	if [ "$a" == "clean" ]; then clean; fi
	if [ "$a" == "lua" ]; then LUA_ENABLED=1; fi
	if [ "$a" == "cp" ]; then CP_ENABLED=1; fi
	if [ "$a" == "pb" ]; then PLUGIN_BUILD=1; fi
	if [ "$a" == "dbg" ]; then DEBUG=1; fi
	if [ "$a" == "wall" ]; then WARN="-Wall"; fi
	if [ "$a" == "nowarn" ]; then WARN="-W0"; fi
	if [ "$a" == "0" ]; then OPT="-O0"; fi
	if [ "$a" == "1" ]; then OPT="-O1"; fi
	if [ "$a" == "2" ]; then OPT="-O2"; fi
	if [ "$a" == "3" ]; then OPT="-O3"; fi
	if [ "$a" == "f" ]; then OPT="-Ofast"; fi
done

if [ $CP_ENABLED -eq 1 ]; then
	CFLAGS="$CFLAGS -DCP_ENABLED"
fi

if [ $LUA_ENABLED -eq 1 ]; then
	echo -n "Searching liblua*.a and lua.h..."
	LUA_INCDIR=`dirname $(find /usr -name lua.h -print -quit 2> /dev/null) 2> /dev/null`
	if [ ! -d "$LUA_INCDIR" ]; then
		echo "fail, include directory not found"
		exit 1
	fi
	LUA_LIBFILE=$(find /usr -name liblua*.a -print -quit 2> /dev/null)
	if [ -f "$LUA_LIBFILE" ]; then
		LUA_LIBFILE=$(basename $LUA_LIBFILE .a 2> /dev/null | tail -c +4)
	else
		echo "fail, lua library not found"
	fi
	echo "done"
	CFLAGS="$CFLAGS -I$LUA_INCDIR -DLUA_ENABLED"
	LIBS="$LIBS -l$LUA_LIBFILE"
fi

if [ $DEBUG -eq 1 ]; then
	CFLAGS="$CFLAGS -g"
	OPT="-O0"
fi

echo -n "Compiling..."
OBJDIR="$ROOT/objs"
if [ ! -d "$OBJDIR" ]; then mkdir $OBJDIR; fi
pids=()
cnt=0
for C in `find "$ROOT/code/" -type f -name *.c`
do
	obj="$OBJDIR/$(basename $C .c).o"
	gcc -c $C -o $obj -I"$ROOT/headers" $WARN $OPT $CFLAGS &
	pids+=($!)
	((cnt++))
	if [ $cnt -ge $MAX_WORKERS ]; then
		wait ${pids[-1]}
		unset pids[-1];
		((cnt--))
	fi
done

for pid in ${pids[@]};
do
	wait $pid
done
echo "done"

echo -n "Linking..."
LOBJ="-not -name luaplugin.o"
if [ $LUA_ENABLED -eq 1 ];
then
	LOBJ=""
fi

OUTDIR="$ROOT/out"
OBJS=$(find $OBJDIR -name "*.o" $LOBJ -printf "$OBJDIR/%P ")
if [ ! -d "$OUTDIR" ]; then mkdir $OUTDIR; fi
LNK="gcc -rdynamic"
if [ $PLUGIN_BUILD -eq 1 ]; then
	LNK="gcc -shared"
fi
$LNK -o "$OUTDIR/$OUTBIN" $LIBS $OBJS
echo "done"
