#!/bin/bash
if [ "$CC" = "" ]; then
	CC="gcc"
fi

MAX_WORKERS=10
DEBUG=0
OPT="-O2"
WARN=""
ROOT="."
CC="$CC -fdiagnostics-color=always"
LNK="$CC -rdynamic"
CFLAGS="-pipe -fPIC -funwind-tables"
LIBS="-lz -lpthread -ldl -lcrypto"
OUTBIN="server"
COMMIT_SHA="-DGIT_COMMIT_SHA=\"$(git rev-parse --short HEAD)\""
PLUGIN_BUILD=0
PLUGIN_INSTALL=0
PLUGINS_DIR="$ROOT/out/plugins"

clean () {
	rm -rf objs/* out/server
	exit 0
}

dowait () {
	wait $1
	if [ $? -ne 0 ]; then
		echo -ne "error\nCompiler errors:\n$(cat /tmp/gcc_stderr)\n"
		exit 1
	fi
}

for a in "$@"
do
	if [ $PLUGIN_BUILD -eq 1 ]; then
		if [ ! -n "$PLUGIN_NAME" ]; then
			CFLAGS="$CFLAGS -DPLUGIN_BUILD -Iheaders"
			LNK="$CC -shared"
			PLUGIN_NAME="$a"
			OUTBIN="$a.so"
			ROOT="$a"
		else
			if [ "$a" == "install" ]; then
				PLUGIN_INSTALL=1
				break
			fi
		fi
		continue
	fi
	if [ "$a" == "clean" ]; then clean; fi
	if [ "$a" == "pb" ]; then PLUGIN_BUILD=1; fi
	if [ "$a" == "wall" ]; then WARN="-Wall -Wextra -pedantic-errors"; fi
	if [ "$a" == "nowarn" ]; then WARN="-W0"; fi
	if [ "$a" == "dbg" ]; then DEBUG=1; OPT="-O0"; fi
	if [ "$a" == "o0" ]; then OPT="-O0"; fi
	if [ "$a" == "o1" ]; then OPT="-O1"; fi
	if [ "$a" == "o2" ]; then OPT="-O2"; fi
	if [ "$a" == "o3" ]; then OPT="-O3"; fi
	if [ "$a" == "of" ]; then OPT="-Ofast"; fi
done

if [ $DEBUG -eq 1 ]; then
	CFLAGS="$CFLAGS -g"
	OPT="-O0"
fi

echo -n "Compiling..."
OBJDIR="$ROOT/objs"
OBJS=""
if [ ! -d "$OBJDIR" ]; then mkdir $OBJDIR; fi
echo -n "" > /tmp/gcc_stderr
pids=()
cnt=0
for C in `find "$ROOT/code/" -type f -name *.c ! -name hash.c`; do
	objpath="$OBJDIR/$(basename $C .c).o"
	OBJS="$OBJS $objpath"
	$CC -c $COMMIT_SHA $C -o $objpath -I"$ROOT/headers" $WARN $OPT $CFLAGS 2>> /tmp/gcc_stderr &
	pids+=($!)
	((cnt++))
	if [ $cnt -ge $MAX_WORKERS ]; then
		dowait ${pids[-1]}
		unset pids[-1]
		((cnt--))
	fi
done

for pid in ${pids[@]}; do
	dowait $pid
done
echo -ne "done\nLinking..."
OUTDIR="$ROOT/out"
if [ ! -d "$OUTDIR" ]; then mkdir $OUTDIR; fi
$LNK -o "$OUTDIR/$OUTBIN" $LIBS $OBJS 2>> /tmp/gcc_stderr
if [ $? -ne 0 ]; then
	echo -ne "error\nLinker errors:\n$(cat /tmp/gcc_stderr)\n"
	exit 1
fi

if [ $DEBUG -eq 0 ]; then
	echo -ne "done\nStripping..."
	strip "$OUTDIR/$OUTBIN"
fi

if [ $PLUGIN_INSTALL -eq 1 ]; then
	echo -ne "done\nCopying to plugins directory..."
	if [ ! -d "$PLUGINS_DIR" ]; then mkdir $PLUGINS_DIR; fi
	cp "$OUTDIR/$OUTBIN" "$PLUGINS_DIR/$OUTBIN"
	echo "done"
else
	echo "done"
fi

stderrlen=$(wc -c < "/tmp/gcc_stderr")
if [ $stderrlen -gt 0 ]; then
	echo -e "Compiler warnings:\n$(cat /tmp/gcc_stderr)"
fi
exit 0
