#!/bin/bash

MAX_WORKERS=10
DEBUG=0
OPT="-O2"
WARN=""
ROOT="."
LNK="gcc -rdynamic"
CFLAGS="-pipe -fPIC -funwind-tables"
LIBS="-lz -lpthread -ldl"
OUTBIN="server"

PLUGIN_BUILD=0
PLUGIN_INSTALL=0

clean () {
	rm -rf objs/* out/server
	exit 0
}

for a in "$@"
do
	if [ $PLUGIN_BUILD -eq 1 ]; then
		if [ ! -n "$PLUGIN_NAME" ]; then
			CFLAGS="$CFLAGS -DCPLUGIN -Iheaders"
			LNK="gcc -shared"
			PLUGIN_NAME="$a"
			OUTBIN="$a.so"
			ROOT="$a"
		else
			if [ "$a" == "install" ]; then
				PLUGIN_INSTALL=1
				break
			fi
		fi
		continue
	fi
	if [ "$a" == "clean" ]; then clean; fi
	if [ "$a" == "pb" ]; then PLUGIN_BUILD=1; fi
	if [ "$a" == "dbg" ]; then DEBUG=1; fi
	if [ "$a" == "wall" ]; then WARN="-Wall"; fi
	if [ "$a" == "nowarn" ]; then WARN="-W0"; fi
	if [ "$a" == "0" ]; then OPT="-O0"; fi
	if [ "$a" == "1" ]; then OPT="-O1"; fi
	if [ "$a" == "2" ]; then OPT="-O2"; fi
	if [ "$a" == "3" ]; then OPT="-O3"; fi
	if [ "$a" == "f" ]; then OPT="-Ofast"; fi
done

if [ $DEBUG -eq 1 ]; then
	CFLAGS="$CFLAGS -g"
	OPT="-O0"
fi

echo -n "Compiling..."
OBJDIR="$ROOT/objs"
if [ ! -d "$OBJDIR" ]; then mkdir $OBJDIR; fi
pids=()
cnt=0
for C in `find "$ROOT/code/" -type f -name *.c`; do
	obj="$OBJDIR/$(basename $C .c).o"
	gcc -c $C -o $obj -I"$ROOT/headers" $WARN $OPT $CFLAGS &
	pids+=($!)
	((cnt++))
	if [ $cnt -ge $MAX_WORKERS ]; then
		wait ${pids[-1]}
		unset pids[-1]
		((cnt--))
	fi
done

for pid in ${pids[@]}; do
	wait $pid
done
echo -ne "done\nLinking..."

OUTDIR="$ROOT/out"
OBJS=$(find $OBJDIR -name "*.o" -printf "$OBJDIR/%P ")
if [ ! -d "$OUTDIR" ]; then mkdir $OUTDIR; fi
$LNK -o "$OUTDIR/$OUTBIN" $LIBS $OBJS
echo -ne "done\nStripping..."
stript "$OUTDIR/$OUTBIN"
if [ $PLUGIN_INSTALL -eq 1 ]; then
	echo -ne "done\nCopying to plugins directory..."
	cp "$OUTDIR/$OUTBIN" "out/plugins/$OUTBIN"
	echo "done"
else
	echo "done"
fi
